#!/bin/sh
#
# @title Check iNode Usage
# ------------------------------------------------------------------------------------------
# @author Myles McNamara
# @date 12/18/2012
# @version 1.0
# @source http://github.com/tripflex
# @description Check the amount of inodes (files) in a given directory.
# ------------------------------------------------------------------------------------------
# @usage ./checkinodeusage <path>
# ------------------------------------------------------------------------------------------
# @copyright Copyright (C) 2012  Myles McNamara
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------------------------

if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ] || [[ $1 == -* ]]; then
 	echo "Usage: $0 <path>" >&2
 	exit
fi
clear
echo "Checking $1 for iNode usage"
echo "-----------------------------------------------------"
	for d in `find $1 -maxdepth 1 -type d |grep -xv $1 |sort`
	do c=$(find $d |wc -l)
	printf "$c\t\t- $d\n"
	done 
echo "-----------------------------------------------------"	
printf "Total iNodes in ($1): \t\t$(find $1 | wc -l)\n"